# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f53c24ede5f1f5f17562797afd2ae58e"
name = "new-app"
handle = "new-app-1059"
application_url = "https://editing-question-mariah-reid.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://editing-question-mariah-reid.trycloudflare.com/auth/callback",
  "https://editing-question-mariah-reid.trycloudflare.com/auth/shopify/callback",
  "https://editing-question-mariah-reid.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
